# -*- coding: utf-8 -*-
"""multinomial_ANN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EOvizt9sTn_pUdNEEY-SrHzb4QdVyswK
"""

from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. 
from scipy import optimize as opt
import matplotlib.pyplot as plt

df = pd.read_csv("Sleep_Efficiency.csv")
df.head()

age = df["Age"].tolist()
gender = df["Gender"].tolist()
duration = df["Sleep duration"].tolist()
efficiency = df["Sleep efficiency"].tolist()
remSleep = df["REM sleep percentage"].tolist()
lightSleep = df["Light sleep percentage"].tolist()
deepSleep = df["Deep sleep percentage"].tolist()
awakenings = df["Awakenings"].tolist()
caffeine = df["Caffeine consumption"].tolist()
alcohol = df["Alcohol consumption"].tolist()
smoke = df["Smoking status"].tolist()
exercise = df["Exercise frequency"].tolist()

columns = ["ID", "Age", "Gender", "Bedtime", "Wakeup time", "Sleep duration", "Sleep efficiency", "REM sleep percentage", "Deep sleep percentage", "Light sleep percentage", "Awakenings", "Caffeine consumption", "Alcohol consumption", "Smoking status", "Exercise frequency"]

for feature in columns:
    le = LabelEncoder()
    df[feature] = le.fit_transform(df[feature])

df = df.drop(["ID", "Bedtime", "Wakeup time", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17"], axis = 1)
df

Y = df["Caffeine consumption"]
df = df.drop(["Caffeine consumption"], axis = 1)

yle = LabelEncoder()
X = df.to_numpy()
y = Y.to_numpy().transpose()
m,n = X.shape

input_layer_size = n
hidden_layer_size = input_layer_size*2
output_layer_size = len(yle.classes_)